[package]
name = "iso-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
disc_riider = { path = ".." }
clap = { version = "3.2.8", features = ["derive"] }
thiserror = "1.0.40"
binrw = "0.11.2"
