[package]
name = "iso-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
disc_riider = { path = ".." }
clap = { version = "4.5.20", features = ["derive"] }
thiserror = "2.0.9"
binrw = "0.14.0"
